### ISSUE TITLE
Pick random color does not work well with vertical images

### ISSUE THREAD

**Issue by gerroon** [eigenmiao/Rickrack#39]
Please see the video, it keeps sampling from the middle in a narrow range

https://github.com/eigenmiao/Rickrack/assets/8519469/676f5f91-9714-4a27-a521-2f8352188e19

**Comment by eigenmiao** [comment]
Hello Gerroon,
I can't see your video here. I'm not sure if you're referring to the function of extracting colors from images. Recently, I updated the function of extracting colors, and the updated content can be found in this video.

https://www.bilibili.com/video/BV1he411n7jv
【软件更新进度】从图片中自动提取一组色彩（Automatically Extract A Set of Colors from The Image）_哔哩哔哩_bilibili<https://www.bilibili.com/video/BV1he411n7jv>
焰火十二卷（Rickrack）是一款免费开源的调色板软件。它提供了多种功能来生成一组调和色彩，可以为你提供更好的色彩搭配方案。你可以通过色轮选取、图像拾色等方式轻松获得想要的色彩组合。你可以将这些色彩应用到自己的创作，或者分享给他人。我最近重构了一下软件中的色彩提取算法，现在可以自动从图像中提取具有不同饱和度、亮度、以及色相的色彩。这个视频展示了软件在不同图片中提取色彩的效果。Recently I, 视频播放量 2、弹幕量 0、点赞数 0、投硬币枚数 0、收藏人数 0、转发人数 0, 视频作者 本征喵函数, 作者简介 个人主页：eigenmiao.com，相关视频：【个人项目】我用 Python 做了一个调色板软件，可以搭配出不同风格的色彩，b站视频提取音频教程，【个人项目】焰火十二卷调色板软件 v2.8.35 更新，更新了界面布局，新增了 RYB 色彩空间等功能，在 Ubun
www.bilibili.com


________________________________
发件人: gerroon ***@***.***>
发送时间: 2024年1月19日 4:51
收件人: eigenmiao/Rickrack ***@***.***>
抄送: Subscribed ***@***.***>
主题: [eigenmiao/Rickrack] Pick random color does not work well with vertical images (Issue #39)


Please see the video, it keeps sampling from the middle in a narrow range

https://github.com/eigenmiao/Rickrack/assets/8519469/676f5f91-9714-4a27-a521-2f8352188e19

**Comment by gerroon** [comment]
Sorry about that, here is the screenshot, basically sampling always happens where those circles are, it never goes up

![Uploading image.png…]()

**Comment by eigenmiao** [comment]
Thanks for your screenshot, but due to network issues, I cannot see any multimedia content, including videos and images. I can only see your description through email. I would like to know if you are referring to an issue in the image view or in the color board view. You can switch between the "Image View" and the "Board View" by pressing "F6" and "F7" (if you haven't changed the shortcut key settings).

If there is only red on the generated color board, you may 1) first need to make sure that not all colors on the color wheel are red. The software generates a color board based on the colors you choose on the color wheel. The circles on the Wheel View, Image View and Board View are interrelated.

2) Then, you may need to check the grid settings in the Mode Sidebar. If you cannot find the Mode Sidebar, click on "Window" at the top of the software and remove other options and keep "Mode" selected. Find the "Grid" option box in the Mode Sidebar and make sure to select "R G B" instead of just "R". If you only choose "R", the generated color palette will only be red. Meanwhile, adjusting the "Sum F" slider can change the influence ranges of circles.

3) Download the color palette example ("demo/02_color_palettes" and "demo/01_color_sets" in the Github repository) to see if it can be used properly.

4) View the software manual: https://eigenmiao.com/2021/12/12/rickrack-tutorial-en-v2.3.4/#Quick-Start
[https://eigenmiao.com/images/rtosac/png/58634816e9c218f19760e7d15cefbaf0.pnglarge.png]<https://eigenmiao.com/2021/12/12/rickrack-tutorial-en-v2.3.4/#Quick-Start>
Tutorial for Rickrack | 喵函数的煎饼铺<https://eigenmiao.com/2021/12/12/rickrack-tutorial-en-v2.3.4/#Quick-Start>
Rickrack is a free and open-source color palette generator. It is designed for generating a set of harmonious colors from color wheel or elsewhere. You can export color sets or color depots into individual files, import them into other softwares (such as Adobe Photoshop, GIMP, Krita, Pencil 2D and Clip Studio Paint).
eigenmiao.com

________________________________
发件人: gerroon ***@***.***>
发送时间: 2024年1月22日 1:23
收件人: eigenmiao/Rickrack ***@***.***>
抄送: 本征喵函数 ***@***.***>; Comment ***@***.***>
主题: Re: [eigenmiao/Rickrack] Pick random color does not work well with vertical images (Issue #39)


Sorry about that, here is the screenshot, basically sampling always happens where those circles are, it never goes up

[Uploading image.png…]

―

**Comment by eigenmiao** [comment]
I finally saw your video. You wanted to extract key colors from a grayscale bar that only changes in brightness. The "**Pick-up Random Colors**" button is actually related to the "**Bright Colorfull**" button in "**Color Extracts**". "**Bright Colorfull**" focuses more on extracting colors of different hues. Maybe you should try other ways of extracting colors, such as "**Bright**".

![GIF 2024-1-30 19-42-27](https://github.com/eigenmiao/Rickrack/assets/59333735/dfcd3198-9157-4a77-afe2-e337e342924f)

The difference between:
* Bright Colorfull
![2 png](https://github.com/eigenmiao/Rickrack/assets/59333735/98fd0bed-0516-46fa-8fea-9c770c331e58)

* Bright Colorfull
![3 png](https://github.com/eigenmiao/Rickrack/assets/59333735/0f2b1205-9212-45ad-a718-88fc3c77cfa6)

* Bright
![4 png](https://github.com/eigenmiao/Rickrack/assets/59333735/1f17531d-dc76-4b1f-8a10-ac3fd2271d01)

**Comment by eigenmiao** [comment]
I will update the color extraction method in the next version (v2.9.x). See:

https://www.bilibili.com/video/BV1he411n7jv/
